### ISSUE TITLE
CRC mismatch makes Arduino board manager download fail.

### ISSUE THREAD

**Issue by truglodite** [ArduCAM/ArduCAM_ESP32S_UNO_PSRAM#3]
Is this still under active development? I can't download the board files in Arduino.

**Comment by Kiri-fr** [comment]
I have the same problem, the board manage fails with CRC error,  OS is windows 10, Arduino version 1.8.15, The board is the Arducam ESP32 UNO PSRAM. Thanks

**Comment by truglodite** [comment]
Yesterday I tried again, and now the board manager link is working as expected. I was able to get the ArduCAM_ESP32S_UNO_PSRAM board loaded up in Arduino 1.8.3 and working. I successfully tested the face detection example code... after fixing a silly error in the example (another PR coming).
